version: '3.3'
services:
  helloworld:
    image: tutum/hello-world
    ports:
     - 8080:80
    logging:
      driver: json-file
    deploy:
      labels:
        ascaler: 'true'
        ascaler.maximum: '4'
        ascaler.minimum: '3'